# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('api_key', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('requests', models.IntegerField(default=0, editable=False)),
            ],
        ),
    ]
